# Generated by Django 5.0 on 2023-12-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskCategory', '0002_remove_taskcategory_taskmodel'),
        ('taskModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_category',
            field=models.ManyToManyField(to='taskCategory.taskcategory'),
        ),
    ]
