# Generated by Django 5.0 on 2023-12-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskCategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='taskmodel',
        ),
    ]
